GoogleCloudPlatform/kubeflow-distribution

kubeflow/Makefile
kubeflow/README.md
kubeflow/hack/create_context.sh
kubeflow/instance/gcp_config/enable-services.yaml
kubeflow/instance/gcp_config/kustomization.yaml
management/hack/create_context.sh

* If we don't enable ASM services ISTIO ingressgateway won't
start and we will get 503s.
* Update instructions
* Provide instructions for installing yq
* Update create_context.sh to allow the namespace to be specified
* Add troubleshooting information for 503s and ASM services not being
enabled.

We need to add a CNRM config to enable ASM services.

---

management/README.md

Fix env var in README.md

---

kubeflow/README.md

Upstream folder's ASM folder also uses location.

Fix upstream folder's location not set

---

kubeflow/Makefile
kubeflow/README.md

* This is a first pass at coming up with a recipe for deploying
Kubeflow using ACM and GitOps.
* There's lots of friction but I was able to get it to work.
* Related to #4

First pass at instructions using ACM

---

management/README.md

Fix cnrm instance commands

---

kubeflow/instance/kustomize/kubeflow-apps/kustomization.yaml
kubeflow/instance/kustomize/kubeflow-apps/pipeline-minio-install-config.yaml

This is corresponding config for https://github.com/kubeflow/manifests/pull/1243

Add minio gcp install config to instance

---

kubeflow/instance/kustomize/kubeflow-apps/kustomization.yaml
kubeflow/instance/kustomize/kubeflow-apps/pipeline-mysql-install-config.yaml

Part of https://github.com/kubeflow/gcp-blueprints/issues/55
Depends on https://github.com/kubeflow/manifests/pull/1286 being merged first

Use gcp stack for blueprint

---

kubeflow/instance/kustomize/kubeflow-apps/kustomization.yaml

Sorry, this is the fix to override the configmap from instance
Fix https://github.com/kubeflow/manifests/issues/1294

fix: add pipeline mysql install config override

---

kubeflow/Makefile

default profile doesn't get an email address, setting it in this PR.

Set user email to default profile

---

prow_config.yaml
tests/pipeline-runs/mnist-nb-pipeline-run.yaml

Run the mnist notebook in the periodic tests.

---

tests/pipeline-runs/mnist-nb-pipeline-run.yaml

* testing-repo is no longer a resource accepted by the pipeline.

Fix the mnist test;

---

kubeflow/Makefile
tests/pipeline-runs/gcp-kf-ready.yaml
tests/pipeline-runs/mnist-nb-pipeline-run.yaml

Pin the manifests to a specific 1.1 tag on the 1.1 branch.

---

prow_config.yaml
tests/pipeline-runs/xgboost-nb-pipeline-run.yaml

Enable xgboost test.

---

kubeflow/Makefile
kubeflow/instance/kustomize/knative/kustomization.yaml

Install knative-serving into its own namespace.

---

kubeflow/Makefile

Need to create the knative-serving namespace in the proper order

---

kubeflow/Makefile

Fixes https://github.com/kubeflow/gcp-blueprints/issues/70
/assign @jlewi

fix: ASM sidecar repeated auth error message to stackdriver

---

kubeflow/Makefile

Related to #89 add KptFile
#46 1.1. release

Update to the the rc1 candidate of manifests.

---

kubeflow/Makefile

Cherry picks #96
/assign @jlewi

Cherry pick of "fix: ASM sidecar repeated auth error message to stackdriver #96"

---

kubeflow/Makefile

Bump manifests to v1.1.0

---

kubeflow/Makefile
management/Makefile

Changes:
1. set-values problem
`make set-values` fail with
```
set-values:
make: set-values:: No such file or directory
make: *** [set-values] Error 1
```
1. remove outdated comment

fix: fix a few problems when deploying e2e

---

kubeflow/Makefile
management/Makefile

Cherry pick of "fix: fix a few problems when deploying e2e #119"

---

management/Makefile

Part of https://github.com/kubeflow/gcp-blueprints/issues/118

Pin v1.1-branch for management cluster

---

README.md

Fix broken link to kpt blueprints page

Fix broken link to kpt blueprints page

---

kubeflow/Makefile
packages/management/Makefile

Part of https://github.com/kubeflow/gcp-blueprints/issues/139
Fixes https://github.com/kubeflow/gcp-blueprints/issues/154
/assign @chensun @subodh101

feat: validate cluster name by regex. Fixes #154

---

docs/dev/release.md

docs: update release doc

---

OWNERS

Add zijianjoy to be OWNERS for GCP resource maintenance.

(org) Add zijianjoy to OWNERS

---

kubeflow/Makefile
kubeflow/common/cloud-endpoints/kustomization.yaml
kubeflow/common/iap-ingress/v3/kustomization.yaml

Fix #221
We are now move away from using application.

(cleanup) Remove application from deployment steps. Fix #221

---

packages/management/cnrm-install/install-system/configconnector-operator.yaml

Fix #219
Following README to update cnrm version

(cnrm) Update cnrm operator version. Fix #219

---

kubeflow/common/istio/kustomization.yaml
kubeflow/pull-upstream.sh

/assign @zijianjoy 
Fixes https://github.com/kubeflow/gcp-blueprints/issues/239

chore: fix pull-upstream.sh, Fixes #239

---

OWNERS

I'm no longer acting as a reviewer so best to remove as an OWNER to help improve code review process.

Remove jlewi@ from OWNERS

---

kubeflow/env.sh
kubeflow/kpt-set.sh

Partial #254.
Feel free to comment. I am going to merge it now.

(env.sh) Move all envrionment variable config to env.sh. Partial #254.

---

kubeflow/apps/pipelines/kustomization.yaml
kubeflow/apps/pipelines/patches/ml-pipeline-ui-deployment-patch.yaml

Fixes https://github.com/kubeflow/gcp-blueprints/issues/261

fix(kfp): kfp ui forward GCP user id header. Fixes #261

---

kubeflow/apps/kfserving/deployment-patch.yaml
kubeflow/apps/kfserving/kustomization.yaml

kfserving: Apply userid-header and userid-prefix patch for KFServing web app. Fix #306

---

management/Makefile

management: Makefile update for management cluster (kpt). Partial #308

---

kubeflow/apps/profiles/kustomization.yaml

profiles: Use upstream profiles image instead of gcp in-house one. Fix #315

---

kubeflow/apps/pipelines/kustomization.yaml
kubeflow/common/cluster/upstream/cluster.yaml
kubeflow/common/cluster/upstream/nodepool.yaml

remove GKE image pin and use emissary executor. Fix #320

---

kubeflow/apps/pipelines/pull-upstream.sh
kubeflow/pull-upstream.sh

pull-upstream: Use the v1.4-branch upstream for now. Fix #302

---

kubeflow/pull-upstream.sh

Context: https://github.com/kubeflow/manifests/issues/2084

manifests: Upgrade to Kubeflow 1.4.1

---

kubeflow/apps/pipelines/pull-upstream.sh
kubeflow/common/iap-ingress/Makefile
kubeflow/pull-upstream.sh

Fix https://github.com/kubeflow/gcp-blueprints/issues/346.

manifests: Upload to Kubeflow 1.5.0-rc.1 and KFP 1.8.0

---

kubeflow/contrib/kserve/Makefile

Changes:
- Reverts the change from #417 
- Prevents #384

Revert kserve makefile changes
