GoogleCloudPlatform/kubeflow-distribution

kubeflow/Makefile
kubeflow/README.md
kubeflow/hack/check_domain_length.sh
kubeflow/instance/gcp_config/kustomization.yaml
kubeflow/upstream/README.md
management/instance/cnrm-install-per-namespace/per-namespace-components.yaml

* Fix some bugs in the blueprints that cropped up while working on
setting up continuous auto-deployments using the blueprints (#5)
Fix some bugs in the documentation.
* Fix bugs in the management config for the per namespace components
of CNRM. The namespaces of the role bindings wasn't correct so
the cnrm manager pod ended up not having appropriate permissions.
* Also the scoped namespace of the cnrm manager statefulset needs
to be set the managed project not the host project.
* Update Makefile to point at kubeflow/manifests master to pull in cert-manager
changes.
* Add check_domain_length to validate the length of the hostname KF
deployment name so that we don't end up exceeding the certificate limits.

Fix various bugs as part of setting up auto deployments

---

kubeflow/Makefile

When running `make apply` in kubeflow blueprint for the second time, it fails in the create IAP secret step, because the secret already exists.
This change update to use the --dry-run -o yaml | kubectl apply -f - trick to make this step idempotent.

Fix apply got secret already exists the 2nd time

---

kubeflow/Makefile
kubeflow/README.md
kubeflow/deploy_private.md
kubeflow/instance/gcp_config/enable-services.yaml
kubeflow/instance/settings.yaml

* Tracking issue #33
* The rules "apply-asm", "apply-gcp", "apply-kubeflow" should all
depend on the hydrate rule; not component specific hydration rules.
* This is because we might want to apply kpt functions as part of hydration
so these commands would be added to the hydration rule and need
to be called before calling the respective apply commands.
* Delete enable-services.yaml we no longer use it; we will use CNRM.
* A bunch of improvements to the Makefile
* Organize it in hydrate and apply sections
* Add a set-values stanza to run all the kpt cfg set commands
* Use if statements to deal with differences e.g. private vs.
non-private deployments
* Need to add this for ASM deployments.

Additional instructions and fixes for private GKE

---

kubeflow/Makefile

* We observe transient failures when deploying kubeflow with the failure
Error from server (InternalError): error when creating ".build/kubeflow-apps/cert-manager.io_v1alpha2_certificate_admission-webhook-cert.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request
* The problem appears to be that the cert-manager webhook isn't available yet
* Add a wait statement to wait for the webhook deployment to be available.

Wait for cert-manager webhook to be created.

---

Makefile
kubeflow/instance/gcp_config/cluster_patch.yaml
kubeflow/instance/gcp_config/nodepool_patch.yaml
kubeflow/instance/kustomize/kubeflow-apps/default-install-config.yaml
kubeflow/instance/kustomize/kubeflow-apps/profiles-config.yaml
kubeflow/instance/settings.yaml

* We need kpt setters in order to properly set the email for the default
profile created.
* Also rerun `clean-for-pr` to clear some of the default values.

Add kpt setters for default profile.

---

kubeflow/Makefile

Add more wait statements for cert-manager.
* Related to: #43
* Looks like this doesn't actually help the cert-manager problem; looks
like we may need to update cert-manager so we can get health checks.
* Use kfctl to apply the cloud endpoints resource; the code for cloud-endpoints-controller should now be baked into kfctl.

Minor tweaks to the Makefile for the blueprint

---

kubeflow/Makefile

This is corresponding Makefile additional commands for https://github.com/kubeflow/manifests/pull/1317.
Part of https://github.com/kubeflow/gcp-blueprints/issues/61
/assign @jlewi

fix(gcp): default workload identity bindings

---

kubeflow/Makefile
kubeflow/README.md

ACM: notebook controller needs to use istio ingress istio-system/ingressgateway

---

kubeflow/Makefile

Reverts kubeflow/gcp-blueprints#99
Because of https://github.com/kubeflow/gcp-blueprints/issues/110

Revert "Cherry pick of "fix: ASM sidecar repeated auth error message to stackdriver #96""

---

kubeflow/Makefile

Reverts kubeflow/gcp-blueprints#96
We reverted the cherry pick, now it seems we just no longer need this in master either.
/assign @rmgogogo @jingzhang36

Revert "fix: ASM sidecar repeated auth error message to stackdriver"

---

management/Makefile

Flag --project has been deprecated, GCE project flag is unused and deprecated

Remove deprecated --project flag from anthoscli

---

kubeflow/instance/kustomize/iap-ingress/kustomization.yaml
kubeflow/instance/kustomize/iap-ingress/service.yaml

`envoy-ingress` backend services unhealthy when installing Kubeflow on GKE version `1.17.9-gke.1504`
Add the `cloud.google.com/neg: '{"ingress": false}'` annotation to `istio-ingressgateway` to disable **container-native load balancing** (neg) which is enabled by default for GKE clusters >= 1.17 ( https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing#using )

Explicitly disable container native load balancing (neg) 

---

tests/validate_test.go

What?
Setting ZONE variable in the hydrate test is missing.
Since we are using the values from the instance to the upstream.
We don't need to set for upstream.
Failing test: https://github.com/kubeflow/gcp-blueprints/pull/155
/cc @Bobgy

Fix kubeflow makefile test

---

kubeflow/Makefile

Fixes https://github.com/kubeflow/gcp-blueprints/issues/160
This should reduce chances of seeing https://github.com/kubeflow/gcp-blueprints/issues/160

feat: kick backend-updater after apply

---

kubeflow/instance/kustomize/iap-ingress/kustomization.yaml
kubeflow/instance/kustomize/iap-ingress/service.yaml

Reverts kubeflow/gcp-blueprints#141
I don't think this annotation fixed the problem per investigation in https://github.com/kubeflow/gcp-blueprints/issues/160
Part of https://github.com/kubeflow/gcp-blueprints/issues/160
/assign @jlewi

Revert "Explicitly disable container native load balancing (neg) "

---

kubeflow/Makefile

Part of https://github.com/kubeflow/gcp-blueprints/issues/139
We should pin v1.2-branch to verify branched content

chore(release): pin kubeflow/manifests v1.2-branch

---

kubeflow/Makefile
kubeflow/instance/Kptfile
tests/validate_test.go

Temporary workaround because of https://github.com/kubeflow/gcp-blueprints/issues/158#issuecomment-731028479
/cc @subodh101 @jlewi 
The goal of this change is that, users can upgrade Kubeflow v1.1 to v1.2 by just
```bash
make update set-values apply
```
So we shouldn't depend on some additional setters not present in Kubeflow v1.1 `instance` folder.
Before the next upgrade, we should be able to use the ideal UX of https://github.com/kubeflow/gcp-blueprints/issues/158#issuecomment-729495722

feat: revert to kf 1.1 installation UX for kubeflow package

---

kubeflow/Makefile

Part of https://github.com/kubeflow/gcp-blueprints/issues/139
Most of the issues raised here were related to errors deploying GCP resources,
so I improved the script to verify those resources are ready.
changes:
* verify all google cloud resources are ready
* show an error message for how to troubleshoot when sth times out

feat: wait for all GCP resources and more helpful error message

---

kubeflow/Makefile
packages/management/Makefile

Fixes https://github.com/kubeflow/gcp-blueprints/issues/164
Upstream issue has been resolved: https://github.com/kubeflow/manifests/pull/1610
So we should be compatible with latest kustomize, right now kustomize 3.8

fix: kustomize 3.8 compatibility

---

kubeflow/Makefile

timeout for cloud build job increased to 30 minutes as it takes a minimum of 20-25 minutes to pull images

fix: increase timeout for gcp cloud build job #185

---

kubeflow/Makefile

Makefile is trying to create the `kubeflow-apps` folder twice.
The second time it should be `kubeflow-istio`.

Fix kubeflow-istio folder creation

---

kubeflow/Makefile
kubeflow/common/cluster/upstream/cluster.yaml
packages/gcp-resources/cnrm/cluster/cluster.yaml

Fix #213 
Fix #214
Prevent future deprecation of GCP dependencies, pin k8s version in Kubeflow 1.3 release.
N1 is going to be deprecated, we will use the equivalent machine type in E2.

(cluster) Use STABLE release channel, change machineType to e2-standard-8. Fix #213, Fix #214

---

kubeflow/apps/profiles/Kptfile
kubeflow/apps/profiles/namespace-labels.yaml
kubeflow/common/asm/Makefile
kubeflow/common/knative/Kptfile
kubeflow/common/knative/patches/namespace-patch.yaml
kubeflow/common/kubeflow-namespace/Kptfile
kubeflow/env.sh
kubeflow/kpt-set.sh

Issue #144
Fix #224 
Document how to pin ASM version in Makefile.
Use kpt cfg set for all ASM namespace labels. The value of these labels `istio.io/rev=asm-XXX-X` need to be consistent across cluster.

(asm) Use kpt to set asm namepsace label, use revision to download install_asm script and package. Issue #144, Fix #224 

---

kubeflow/Makefile
kubeflow/apps/kfserving/Makefile
kubeflow/common/asm/Makefile
kubeflow/common/cert-manager/Makefile
kubeflow/common/cloud-endpoints/kustomization.yaml
kubeflow/common/cnrm/Makefile
kubeflow/common/iap-secret/Makefile
kubeflow/common/knative/Makefile
kubeflow/common/kubeflow-issuer/kustomization.yaml
kubeflow/pull-upstream.sh

Partial #230
This PR implements the core functionality of #230 - `make apply`
The way to initialize and deploy:
1. set all values in env.sh and kpt-set.sh
2. Set CLIENT_ID and CLIENT_SECRET
3. $ source env.sh
4. $ bash ./pull-upstream.sh
5. $ bash kpt-set.sh
6. $ make apply-v3
Rules like `hydrate`, `delete`, `clean-build` are not implemented yet. We need to remove existing rule in Makefile later on.

(Makefile) Run make apply-v3 to apply all components and deployment steps. #230

---

kubeflow/apps/katib/kustomization.yaml
kubeflow/pull-upstream.sh

Fix #233
Change upstream tag to 1.3.0
Change Katib target.
Validated that RStudio trademark is removed.

(kubeflow/manifests) Upgrade upstream to Kubeflow 1.3. Fix #233

---

kubeflow/common/cluster/upstream/cluster.yaml

Fix #243
Screenshot for the deployment:

(Cluster) Set starting k8s version to be 1.18. Fix #243

---

management/Kptfile
management/managed-project/README.md
management/managed-project/iam.yaml

Partial #252
I need another GCP project to validate this fix. But based on the existing material, I am able to bring back the iam.yaml file from last cleanup.
Submitting this change for now, feel free to comment later on.

(management) Add managed project IAM file and kptfile. Partial #252

---

kubeflow/common/iap-ingress/base/cluster-role.yaml
kubeflow/common/iap-ingress/base/config-map.yaml

Unhealthy backend due to misconfigured health check.
The `iap-backendconfig` BackendConfig healthCheck spec points to the wrong port. It overwrites `backend-updater` changes.
Refactor `update_backend.sh` script (used by `backend-updater` stateful set) to patch the BackendConfig `iap-backendconfig` healthcheck port instead of updating the health-check resource directly.

(iap-ingress) Patch BackendConfig healthcheck port with the correct port number

---

kubeflow/apps/profiles/kustomization.yaml
kubeflow/apps/profiles/namespace-labels.yaml
kubeflow/apps/profiles/patches/manager.yaml
kubeflow/apps/profiles/patches/namespace-labels.yaml

This is our current way to adopting https://github.com/kubeflow/kubeflow/pull/5761/files.
I am able to create profile and add contributor via UI and yaml file.
Note that even though I have added sidecar injection label ` istio.io/rev=asm-192-2` to kubeflow namespace. I am not able to inject sidecar for KFP yet. It might not be related to this PR.

(profile-controller) Adopt v1.3.0-gcp profile controller 

---

kubeflow/common/cnrm/Makefile

Fix #252
We are removing a command to set namespace for management-cluster context, therefore we need to make sure the kubectl command in Makefile is specifying namespace.

(management) Specify namespace in wait-gcp command. Fix #252

---

kubeflow/common/asm/Makefile
kubeflow/env.sh

Preparing for Kubeflow 1.3 release, we need to make sure ASM is using the latest version.

(ASM) Upgrade ASM to latest available version

---

kubeflow/common/cluster/upstream/cluster.yaml

Reference: https://github.com/kubeflow/pipelines/issues/5714
Make sure that Kubeflow cluster is using docker image type, otherwise pipeline will fail. 
Also related: https://github.com/kubeflow/gcp-blueprints/issues/271#issuecomment-846299401

[KF 1.3.1] Pin image type to be docker

---

kubeflow/pull-upstream.sh

Reference: https://github.com/kubeflow/manifests/issues/1949
Note: 
The integration with istio on manifests needs update, it has changed its folder naming.
Consider upgrading ASM version in the 1.4 release, integration with ASM 1.10.2 looks to be straightforward so far.

(release): Upgrade from Kubeflow 1.3.0 to 1.3.1

---

Makefile
kubeflow/apps/kfserving/Kptfile
kubeflow/apps/pipelines/Kptfile
kubeflow/apps/pipelines/Makefile
kubeflow/apps/pipelines/gcs/pipeline-install-config-patch.yaml
kubeflow/apps/pipelines/kustomization.yaml
kubeflow/apps/pipelines/pull-upstream.sh
kubeflow/kpt-set.sh
kubeflow/pull-upstream.sh

Part of https://github.com/kubeflow/pipelines/issues/5680
Depends on https://github.com/kubeflow/pipelines/pull/5750
Changes:
* configure default pipeline root to gcs bucket using a new kpt setter `default-pipeline-root`
* extract KFP specific pull-upstream script to its own folder, so that admin can only update KFP and deploy

feat: make KFP v2 compatible mode work out of the box

---

kubeflow/apps/profiles/kustomization.yaml
kubeflow/apps/profiles/label-transformer.yaml
kubeflow/common/knative/kustomization.yaml
kubeflow/common/knative/label-transformer.yaml

Fix #298.
- Remove knative-serving namespace in kustomization, it updated knative-local-gateway to deploy in istio-system namespace.
- Use labelTransformer to allow knative-local-gateway to select istio-ingressgateway.

kustomize: Use labelTransformer to replace commonLabels. Fix #298

---

kubeflow/apps/pipelines/pull-upstream.sh
kubeflow/pull-upstream.sh

Fix #309
Partial #317, #308, #302.
TODO:
- Wait for new manifests RC for training-operator fix.
- Wait for new kpt to be ready so we can document it.
- Download from manifests upstream instead of zijianjoy/pipelines repo

Upgrade kpt 1.0.0-beta.6 and Kubeflow manifests 1.4.0-rc.1. Fix #309

---

kubeflow/apps/pipelines/pull-upstream.sh
kubeflow/apps/profiles/patches/namespace-labels.yaml

Related issues:
https://github.com/kubeflow/pipelines/issues/7336
I need to add a missing katib enabled annotation to user namespace in order to be able to create AutoML experiment.

fix(katib, pipelines): Use KFP 1.8.1-rc.0, and enable katib in user namespaces

---

kubeflow/apps/pipelines/cloudsql/cnrm/iam.yaml
kubeflow/apps/pipelines/cloudsql/cnrm/proxy-gsa.yaml
kubeflow/apps/pipelines/cloudsql/proxy/workload-identity-binding-patch.yaml

fix the name length restriction #358

cloudsql: Use a shorter cloudsql service account name to allow longer Kubeflow name

---

kubeflow/pull-upstream.sh

create kserve directory to store upstream files and prevent `no such file or directory` error

fix(pull-upstream): create kserve directory to store upstream files

---

kubeflow/apps/centraldashboard/kustomization.yaml
kubeflow/config.yaml
kubeflow/contrib/kserve/kustomization.yaml
kubeflow/contrib/kserve/patches/web-app-vsvc.yaml

Fix https://github.com/kubeflow/manifests/issues/2180
1. Central dashboard should have used the upstream/overlays/kserve.
2. Provide an option to switch to kfserving overlay on central dashboard.
3. Remove a previous patch which is conflicting with virtual service prefix set by kserve.

kserve: Use correct configuration for showing model-web-apps from kserve on central dashboard

---

kubeflow/common/iap-ingress/base/config-map.yaml
kubeflow/common/iap-ingress/base/kustomization.yaml
kubeflow/common/iap-ingress/base/policy.yaml

In my gitops setup I was facing a race condition between `Fluxcd` and `iap-enabler` where they were both updating the `ingress-jwt` RequestAuthentication resource:
- Fluxcd creates/updates the `ingress-jwt` RequestAuthentication resource without the audience (TO_BE_PATCHED)
- `iap-enabler` resolves the backend id and patches the `ingress-jwt` audience
Move `ingress-jwt` RequestAuthentication creation logic to `iap-enabler`.
- Move `policy.yaml` from Kustomize resources list to `envoy-config` ConfigMap
- Refactor `setup_backend.sh` to replace `TO_BE_PATCHED` with the correct audience and apply `policy.yaml` to create/update `ingress-jwt`

Move `RequestAuthentication` policy creation to `iap-enabler` for gitops friendliness

---

kubeflow/asm/Makefile
kubeflow/asm/README.md
kubeflow/asm/deprecated/Makefile
kubeflow/asm/deprecated/README.md
kubeflow/common/iap-ingress/base/config-map.yaml
kubeflow/env.sh
kubeflow/pull-upstream.sh

Upgrading ASM to 1.13:
- Changed installation process to use `asmcli` tool instead of `install_asm` tool
- Using `istio-1-11` from Manifests as it is currently sufficient. Planning to switch to `istio-1-14` once ASM v 1.14 is released
- Updated healthCheck configuration:
- New requestPath: /healthz
- New port: "http2"
Tested run on [end-2-end MNIST example](https://github.com/kubeflow/pipelines/blob/master/samples/contrib/kubeflow-e2e-mnist/kubeflow-e2e-mnist.ipynb)

Upgrade ASM to v1.13

---

kubeflow/apps/pipelines/pull-upstream.sh
kubeflow/asm/Makefile
kubeflow/common/iap-ingress/Makefile
kubeflow/contrib/application/kustomization.yaml
kubeflow/contrib/kserve/Makefile
kubeflow/env.sh
kubeflow/pull-upstream.sh

Preparing for KF 1.6.0 release on GCP:
- Updated upstream [Manifests](/kubeflow/manifests) to v1.6.0
- Upgraded ASM to 1.14.1 to match Istio in [Manifests](/kubeflow/manifests) to v1.6.0
- Upgraded KFP to 2.0.0-alpha.4. Now KFP version and repo have to be set in the main **kubeflow/pull-upstream.sh** instead of **kubeflow/apps/pipelines/pull-upstream.sh**
- Fixed Kserve race condition during deployment
- Added an extra delay that ensures 30+ sec execution for `backend-updater`, `iap-enabler`, and `cloud-endpoints-enabler` workloads to improve deployment stability
- Changed upstream for **contrib/metacontroller** to [KFP](/kubeflow/pipelines)
- Deprecated and removed **contrib/application**
Testing:

Upgrade to v1.6.0

---

kubeflow/apps/pipelines/kustomization.yaml
kubeflow/apps/pipelines/patches/ml-pipeline-persistenceagent-deployment-patch.yaml

https://github.com/kubeflow/pipelines/pull/7819 add `KUBEFLOW_USERID_HEADER` and `KUBEFLOW_USERID_PREFIX` in upstream `persistenceagent` deployment config. 
Without this patch, the upstream config causes a mismatch of header and prefix choices between `api-server` and `persistenceagent`, which fails authorization check in `ReadArtifact`.
Fixes #392

Add persistenceagent deployment patch to fix metrics read error. Fixes #392

---

CHANGELOG.md
kubeflow/apps/pipelines/kustomization.yaml
kubeflow/asm/Makefile
kubeflow/common/iap-ingress/Makefile
kubeflow/common/managed-storage/cloudsql/sql-instance.yaml
kubeflow/pull-upstream.sh

Upgrading Kubeflow distribution for 1.6.1 release:

Releasing GCP Kubeflow distribution v1.6.1

---

kubeflow/common/knative/knative-1-8-5/net-istio.yaml
kubeflow/common/knative/knative-1-8-5/serving-core.yaml
kubeflow/common/knative/knative-1-8-5/serving-crds.yaml
kubeflow/common/knative/kustomization.yaml

Previous upgrade: [KNative 1.2](https://github.com/GoogleCloudPlatform/kubeflow-distribution/pull/373/)
- Upgraded `serving` to 1.8.5
- Upgraded `net-istio` to 1.8.3
Full testing on GKE 1.24 or 1.25 will be done once all components will be upgraded.
I chose `1.8.5` over `1.8.1` as the latest patches [included](https://github.com/knative/serving/releases) numerous vulnerability fixes.

Upgrade KNative to 1.8.5. Closes #404

---

kubeflow/asm/Makefile
kubeflow/env.sh

Previous upgrade: [ASM 1.13](https://github.com/GoogleCloudPlatform/kubeflow-distribution/pull/369)
- Upgraded ASM to `1.16.2-2`
Full testing on GKE 1.24 or 1.25 will be done once all components will be upgraded.
I am still using `istio-1-14` manifests from the upstream. They will be upgraded once we switch to the 1.7 tag of `kubeflow/manifest`. Both options are fully-functional on GKE `1.23`.
**Note:** merge after #409 and #410

Upgrade ASM to 1.16.2-2. Closes #406

---

kubeflow/apps/katib/deployment-patch.yaml
kubeflow/apps/katib/kustomization.yaml

- Added a patch to `katib-ui` deployment
Reference: https://github.com/kubeflow/katib/issues/2126

fix(katib): Add user header to address #414

---

kubeflow/common/cluster/upstream/nodepool.yaml

The clusterName is no longer required here and just causes errors when trying to deploy Kubeflow on GCP.  Remove this line:
```
clusterName: "PROJECT/LOCATION/KUBEFLOW-NAME" # kpt-set: ${gcloud.core.project}/${location}/${name}
```

Remove clusterName from nodepool.yaml

---

kubeflow/common/cluster/upstream/cluster.yaml

This line is just causing problems in the GCP deployment. It is no longer needed in this release at all. Removing it:
clusterName: "PROJECT/LOCATION/KUBEFLOW-NAME" # kpt-set: ${gcloud.core.project}/${location}/${name}

remove metadata.clusterName entirely from cluster.yaml

---

kubeflow/common/cnrm/cluster-patch.yaml
kubeflow/common/cnrm/nodepool-example.yaml

Changes:
- Fixed SA format `ContainerNodePool`
- Added a sample `spec.nodeConfig.machineType` for `ContainerCluster` to avoid confusion

Fix SA and add machine type to ContainerCluster. Closes #432.

---

kubeflow/hack/apply_component.sh

fixes #440 
Adds a line to remove generated lines containing `creationTimestamp: "null"`, during kubectl having trouble reading them.

auto remove lines with `creationTimestamp: "null"`
